### ISSUE TITLE
Error installing shard

### ISSUE THREAD

**Issue by teodor-pripoae** [juanedi/micrate#1]
Hi,

I'm getting an error when installing the shard

```
dependencies:
  github: juanedi/micrate
```

```
Updating https://github.com/juanedi/micrate.git
git command failed: git ls-tree -r --full-tree --name-only v0.1.0 -- shard.yml (). Maybe you didn't install git?
```

You published the wrong tag. Tags must be prefixed with `v`. You should use `v0.1.0` instead of `0.1.0`.

**Comment by asterite** [comment]
@ysbaddaden can we maybe make shards check both variants? Why is it `v0.1.0` instead of just `0.1.0`?

**Comment by ysbaddaden** [comment]
It took an initial `v` for many reasons: personal habit, GitHub recommends it on the releases page, most Bower libraries I use set the initial `v` (thought Bower supports both), ... I guess Shards could support both, it complicates the Git resolver that will have to check _both_ namings whenever dealing with version tags, but it's doable.

**Comment by asterite** [comment]
@ysbaddaden As you wish. I think checking both versions, even if a bit slower, will make developers life happier, as one doesn't have to learn that you have to prefix tags with `v`.

**Comment by juanedi** [comment]
Just fixed the release. Sorry about the delay!
