### ISSUE TITLE
config.yml for multi db

### ISSUE THREAD

**Issue by sdogruyol** [juanedi/micrate#3]
Hey there,

This is pretty cool. I intended to write something like this but you already have done a great job 👍 

How about configuration? Something like `config.yml` would be great.

**Comment by juanedi** [comment]
Thanks, I'm glad you liked it!

Are you thinking about having different connection URLs per environment (test, development, production)?

If that's the case, my first impression is that those environments are something your application should know about, but probably not this tool. If we had a micrate-specific configuration file then any app that uses micrate should do one of the following:

- Duplicate that configuration to set up their database for normal app usage
- Be forced to read it's DB configuration from micrate's file

In that case I believe it's probably better to have your application be configured any way you want, and have it set up micrate doing something like this:

```crystal
# You could let the user configure your API any way you want
Micrate::DB.connection_url = MyApp::Settings.database_url

# Run CLI
Micrate::Cli.run

# OR use programatic API
Micrate::DB.connect do |db|
  Micrate.up(db)
end
```

I think this gives apps/frameworks that use this tool more flexibility. Am I missing something?
Are you thinking about a specific setting that cannot be expressed in the connection URL?

**Comment by sdogruyol** [comment]
At second thought, you are right 👍 

It's applications' responsibility to know about the environment and not Micrate.
