### ISSUE TITLE
A  question about this project.

### ISSUE THREAD

**Issue by timuckun** [juanedi/micrate#4]
Hi Juan.

I was just looking at the source code for this project and wanted to ask you about it. 

The first question is why by default it breaks up  the SQL into multiple statements by default. Is there some advantages to that?  I can't think of any reason why that would be preferable to just sending over a large SQL with all the statements in one shot. It would be faster and more transactionally safe. I know you used the go project so maybe that's why but maybe I am missing something. If you got rid of that it would simplify the parsing a great deal too. 

Also for those times when you want to create a migration file manually it would be easier to have the markers be simpler like --+up and --+down or even --^ and --v 

Thanks for writing it! I am learning crystal and it was instructional to read the code.

**Comment by juanedi** [comment]
Hello Tim! I'm glad you found this useful.

The project started as a (quick but functional) port from goose restricted to postgres. So I admit I didn't give that part much thought then.

Right now the only advantage I can think of executing the statements one at a time is the possibility of having a more detailed trace of the execution of the migration (even though we are not doing it right now). Note that we could still wrap the migrations in a transaction without needing to execute the script as a whole. On the other hand, I agree that we should drop the parsing code regarding if we can do without it.

I believe it is a priority to have micrate use the [crystal db](https://github.com/crystal-lang/crystal-db) API so we can target more databases (there is a working branch, but I still want to check the state of the available drivers and think about what will happen to the prebuilt executable). Maybe we can pick this (and the transaction issue) up later. I wouldn't want to make any postgres-driver specific changes for the moment.

Thanks for the comment! I hadn't thought about this before.

**Comment by rdp** [comment]
+1 for sqlite support here :)

**Comment by juanedi** [comment]
@rdp Check out the latest release which includes support for SQLite and MySQL :)

**Comment by juanedi** [comment]
Closing this. For the moment I can't see a strong reason change the tool to run the scripts as a whole. Other databases are already supported and transaction support will be tracked in #11.
