### ISSUE TITLE
Schema Generation

### ISSUE THREAD

**Issue by jwoertink** [juanedi/micrate#6]
Is there a way to generate some sort of schema file that could be ran later to re-build a DB? If not, are there any plans to add this in?

**Comment by juanedi** [comment]
Hi! Sorry for the delay.

I assume you mean something similar to active record's `schema.rb`.

To be honest I believe having to recreate the schema each time based on migrations ensures that you won't have any inconsistency between the migrations and the schema file. I had to deal with this problems in large projects with lots of migrations and it's a pain.

I think I prefer having this "only source of truth", unless there's a use case that cannot be achieved.

What use case do you have in mind?

**Comment by jwoertink** [comment]
I wasn't necessarily thinking about something like the schema.rb. I'm more thinking about the case of a test DB. Let's say you want to run specs against a test DB. You run some script that builds the DB based on the schema. Then you could drop the database completely, and re-create it at any time by loading the schema. This would be different from a normal database dump because in development or test, you may not want the data to be imported. 

Let me know if that makes sense.

**Comment by juanedi** [comment]
For cases like these I have used a Makefile like with a task like this one:

```Makefile
db_test_prepare:
	@dropdb --if-exists $(TEST_DB)
	@createdb -E utf8 -O `whoami` $(TEST_DB)
	@PG_URL="postgres://`whoami`@localhost/$(TEST_DB)" bin/micrate up
```

This runs the migrations each time the test database is set up, but I don't really think that's a problem. To avoid doing this every time, you could combine it with cleaning up all data before running the specs.

Also, note that you can also use the `-s` flag in `pg_dump` to create a schema-only dump it you wanted to.

Would any of these work?
